---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Visualizing a Torus Knot Fibration"
keywords:    "Torus, Knot, Fibration, Mathematica, Visualizing"
description: "Summer Project for my Master's in Mathematics at University of Toronto Supervised by Dror Bar-Natan"
source_link: "https://github.com/jessebett/TorusKnotFibration"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
#google_analytics_key:  ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

